name: _
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/code_gen_tester
  - packages/functional_widget
  - packages/functional_widget/example
  - packages/functional_widget_annotation
  - packages/functional_widget_annotation/example
