builders:
  functional_widget_generator:
    import: "package:functional_widget_generator/builder.dart"
    builder_factories: ["functionalWidget"]
    build_extensions: { ".dart": [".functional_widget.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
