# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings lib test
  - unit_test:
    - test
    - command: pub run test_coverage
    - command: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - .dart_tool/build