# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-infos --fatal-warnings lib test
  - unit_test:
    - group:
      - test

cache:
  directories:
  - .dart_tool/build