# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyzer_and_format:
    - group:
      - dartfmt
      - command: flutter analyze --no-pub --no-preamble
  - unit_test:
    - command:  flutter pub pub run test

cache:
  directories:
  - .dart_tool/build