targets:
    $default:
        builders:
            functional_widget:
                enabled: true
                generate_for:
                    include:
                        - example/lib/*
builders:
    functional_widget:
        import: 'package:functional_widget/builder.dart'
        builder_factories: ['functionalWidget']
        build_extensions: { '.dart': ['.functional_widget.g.part'] }
        auto_apply: dependents
        build_to: cache
        applies_builders: ['source_gen|combining_builder']
