name: code_gen_tester
version: 0.0.1

environment:
  sdk: ^2.12.0

dependencies:
  test: ^1.15.4
  dart_style: ^2.0.0
  pedantic: ^1.9.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  analyzer: ^2.2.0
  build: ^2.0.0
  build_config: ^1.0.0
  meta: ^1.2.0
  functional_widget_annotation: ^0.9.0
  source_gen: ^1.0.0
  code_builder: ^4.0.0
