name: code_gen_tester
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  test: ^1.15.4
  dart_style: ^3.0.0
  pedantic: ^1.9.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  analyzer: ">=6.9.0 <8.0.0"
  build: ^2.0.0
  build_config: ^1.0.0
  meta: ^1.2.0
  functional_widget_annotation:
  source_gen: ^2.0.0
  code_builder: ^4.0.0
